'use client'

import { Inter } from 'next/font/google'
import Header from './components/Header'
import './globals.css'
import Footer from './components/Footer'
import Aviso from './components/Aviso'
import Main from "./components/Main";
import { useEffect } from "react";

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  useEffect(() => {
    const mainElement = document.querySelectorAll(".mainClass");
    mainElement.forEach((element) => {
      element.style.opacity = "0";
      element.style.pointerEvents = "none";
    });
  }, []);

  return (
    <html lang="pt-br">
      
      <body className={inter.className}>
        <Aviso  />
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
